version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    network_mode: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis:alpine
    network_mode: host
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
    postgres: